let alphabet = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]

// 26 alphabet
let password = alphabet[Int.random(in: 0...25)]+alphabet[Int.random(in: 0...25)]+alphabet[Int.random(in: 0...25)]+alphabet[Int.random(in: 0...25)]+alphabet[Int.random(in: 0...25)]+alphabet[Int.random(in: 0...25)]
   
   print("\(password) is a Password generated by a Computer")
   
